"""Initial schema with intake sessions and simulations

Revision ID: 93d967cc8e9a
Revises: 
Create Date: 2026-03-06 23:07:52.107505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d967cc8e9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('collected_data', sa.JSON(), nullable=True),
    sa.Column('simulation_ready', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_sessions_id'), 'intake_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_session_id'), 'intake_sessions', ['session_id'], unique=True)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('passport', sa.String(length=10), nullable=True),
    sa.Column('age_bracket', sa.String(length=20), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('profession_category', sa.String(length=100), nullable=True),
    sa.Column('migration_goal', sa.String(length=50), nullable=True),
    sa.Column('target_country', sa.String(length=10), nullable=False),
    sa.Column('time_horizon_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['intake_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_index(op.f('ix_simulations_simulation_id'), 'simulations', ['simulation_id'], unique=True)
    op.create_table('timeline_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(length=100), nullable=False),
    sa.Column('phase_name', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.Float(), nullable=False),
    sa.Column('end_year', sa.Float(), nullable=False),
    sa.Column('visa_or_status', sa.String(length=200), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('key_constraints', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.simulation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_phases_id'), 'timeline_phases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_phases_id'), table_name='timeline_phases')
    op.drop_table('timeline_phases')
    op.drop_index(op.f('ix_simulations_simulation_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_intake_sessions_session_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_id'), table_name='intake_sessions')
    op.drop_table('intake_sessions')
    # ### end Alembic commands ###
